/**
 * Writes work/browsers/chrome-for-testing -- a tiny launcher pointing at the
 * Chrome for Testing build Playwright already downloaded.
 *
 * Why this exists: Google Chrome (stable, dev and canary alike, verified on 152)
 * no longer honours the --load-extension command-line switch, so a launch
 * configuration pointing at /Applications/Google Chrome.app opens a browser with
 * no extension in it. Chrome for Testing still honours the switch.
 *
 * The generated file is a shell wrapper rather than a symlink so macOS resolves
 * the .app bundle's frameworks from their real location, and it is regenerated
 * rather than committed because the path carries Playwright's build number.
 *
 * Run with `npm run browser:link` (the VS Code launch tasks do this for you).
 */
import { chromium } from "playwright-core";
import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TARGET = resolve(ROOT, "work", "browsers", "chrome-for-testing");

const executable = chromium.executablePath();
if (!executable) {
    console.error("No Chromium found. Run: npm run playwright:install-browsers");
    process.exit(1);
}

mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(TARGET, `#!/bin/sh\n# Generated by tasks/link-browser.mjs -- do not edit.\nexec "${executable}" "$@"\n`);
chmodSync(TARGET, 0o755);

console.log(`work/browsers/chrome-for-testing -> ${executable}`);
